In [13]:
import pandas as pd
from datetime import datetime
import pickle
import os

In [14]:
with open('semanas.pkl', 'rb') as archivo:
    variable_cargada = pickle.load(archivo)
variable_cargada["307"] = "SEMANA 42/2023 (del 09/10/2023 al 15/10/2023)"
variable_cargada["308"] = "SEMANA 43/2023 (del 16/10/2023 al 22/10/2023)"
variable_cargada["309"] = "SEMANA 44/2023 (del 23/10/2023 al 29/10/2023)"
variable_cargada["310"] = "SEMANA 45/2023 (del 30/10/2023 al 05/11/2023)"
variable_cargada["311"] = "SEMANA 46/2023 (del 06/11/2023 al 12/11/2023)"
variable_cargada["312"] = "SEMANA 47/2023 (del 13/11/2023 al 19/11/2023)"
variable_cargada["313"] = "SEMANA 48/2023 (del 20/11/2023 al 26/11/2023)"
variable_cargada["314"] = "SEMANA 49/2023 (del 27/11/2023 al 03/12/2023)"
variable_cargada["315"] = "SEMANA 50/2023 (del 04/12/2023 al 10/12/2023)"
variable_cargada["316"] = "SEMANA 51/2023 (del 11/12/2023 al 17/12/2023)"
variable_cargada["317"] = "SEMANA 52/2023 (del 18/12/2023 al 24/12/2023)"
variable_cargada["318"] = "SEMANA 53/2023 (del 25/12/2023 al 31/12/2023)"
variable_cargada["319"] = "SEMANA 01/2024 (del 01/01/2024 al 07/01/2024)"
variable_cargada["320"] = "SEMANA 02/2024 (del 08/01/2024 al 14/01/2024)"
variable_cargada["321"] = "SEMANA 03/2024 (del 15/01/2024 al 21/01/2024)"
variable_cargada["322"] = "SEMANA 04/2024 (del 22/01/2024 al 28/01/2024)"
variable_cargada["323"] = "SEMANA 05/2024 (del 29/01/2024 al 04/02/2024)"
variable_cargada["324"] = "SEMANA 06/2024 (del 05/02/2024 al 11/02/2024)"
variable_cargada["325"] = "SEMANA 07/2024 (del 12/02/2024 al 18/02/2024)"
variable_cargada["326"] = "SEMANA 08/2024 (del 19/02/2024 al 25/02/2024)"
variable_cargada["327"] = "SEMANA 09/2024 (del 26/02/2024 al 03/03/2024)"
variable_cargada["328"] = "SEMANA 10/2024 (del 04/03/2024 al 10/03/2024)"
variable_cargada["329"] = "SEMANA 11/2024 (del 11/03/2024 al 17/03/2024)"
variable_cargada["330"] = "SEMANA 12/2024 (del 18/03/2024 al 24/03/2024)"
variable_cargada["331"] = "SEMANA 13/2024 (del 25/03/2024 al 31/03/2024)"

In [15]:
columnas = ["nombre","ultimos_7_dias_anterior","ultimos_7_dias",
            "ultimos_7_dias_abs","ultimos_7_dias_var","ultimos_28_dias_anterior","ultimos_28_dias",
            "ultimos_28_dias_abs","ultimos_28_dias_var","anno_a_la_fecha_anterior","anno_a_la_fecha",
            "anno_a_la_fecha_abs","anno_a_la_fecha_var","Delito","nombre1","nombre2","COD_CUADRANTE_INTERNO",
            "semmana_interna"]

carabinero = pd.read_excel(r"C:\Users\limc_\carabineros\carabineros.xlsx")
carabinero= carabinero[carabinero["ZONA"] == 'METROPOLITANA']

In [16]:
"""
columnasRef = ['semana', 'semana ant', 'semana var', 'semana var%', 'mes', 'mes ant',
       'mes var', 'mes var%', 'año', 'año ant', 'año var', 'año var%',
       'delito', 'informacion', 'id_semana', 'actual-año', 'anterior-año',
       'Cuad_titulo', 'CUA_CODIGO', 'type', 'features', 'CUA_SUP', 'COMUNA',
       'UNIDAD', 'DESTACAMEN', 'PREFECTURA', 'ZONA', 'NUM_CUAD', 'CUA_DESCRI',
       'CUA_TIPO', 'CUA_ESTADO', 'CUA_FTERMI', 'UNI_CODIGO', 'CUA_ANO',
       'COD_AUPOL', 'COM_CODIGO', 'SHAPE_LENG', 'SHAPE_AREA', 'COD_DESTAC',
       'TOOLTIP', 'COD', 'SUP_KM2', 'FechaInicial', 'FechaFinal',
       'COD_CUADRANTE_INTERNO']
"""
columnasRef = ['semana', 'semana ant', 'semana var', 'semana var%', 'mes', 'mes ant',
       'mes var', 'mes var%', 'año', 'año ant', 'año var', 'año var%',
       'delito', 'informacion', 'id_semana', 'actual-año', 'anterior-año',
       'Cuad_titulo', 'CUA_CODIGO', 'COMUNA',
       'UNIDAD', 'DESTACAMEN', 'PREFECTURA', 'ZONA', 'NUM_CUAD', 'CUA_DESCRI',
       'CUA_TIPO', 'CUA_ESTADO', 'CUA_FTERMI', 'UNI_CODIGO', 'CUA_ANO',
       'COD_AUPOL', 'COM_CODIGO', 'COD_DESTAC',
       'FechaInicial', 'FechaFinal',
       'COD_CUADRANTE_INTERNO']
diccionarioColumnas = {
                        'ultimos_7_dias_anterior':'semana ant',
                        'ultimos_7_dias':'semana', 
                        'ultimos_7_dias_abs':'semana var',
                        'ultimos_7_dias_var':'semana var%', 
                        'ultimos_28_dias_anterior': 'mes ant', 
                        'ultimos_28_dias':'mes',
                        'ultimos_28_dias_abs':'mes var', 
                        'ultimos_28_dias_var':'mes var%',
                        'anno_a_la_fecha_anterior':'año ant', 
                        'anno_a_la_fecha':'año', 
                        'anno_a_la_fecha_abs':'año var',
                        'anno_a_la_fecha_var':'año var%', 
                        'Delito':'informacion',
                        'nombre':'delito',
                        'semana':'id_semana',
                        'actual':'actual-año',
                        'anterior':'anterior-año',
                        'titulo':'Cuad_titulo'
                        }

web = pd.read_excel(r"C:\Users\limc_\carabineros\web_cuadrantes.xlsx",sheet_name="aparte")
diccionarioWeb = {}
for j,i in web[["codigo_cuadrante","codigo_comuna"]].iterrows():
    diccionarioWeb[i["codigo_cuadrante"]] = i["codigo_comuna"]

def getComunasAparte(fila):
    try:
        return diccionarioWeb[int(fila["COD_CUADRANTE_INTERNO"])]
    except:
        return fila["COM_CODIGO"]    

    
diccionarioWeb

{4375001: 13202,
 4375002: 13202,
 4376156: 13202,
 4376157: 13202,
 4376161: 13202,
 4376801: 13202,
 3934802: 13302,
 3934002: 13302,
 3934804: 13302,
 3934803: 13302,
 3934001: 13302,
 3934801: 13302,
 31720371: 13301,
 31720372: 13301,
 31720381: 13301,
 31720382: 13301,
 31720391: 13301,
 31720392: 13301,
 3172801: 13301,
 3172802: 13301,
 31720361: 13301,
 31720362: 13301,
 31720363: 13301,
 32951221: 13123,
 32951411: 13123,
 32950253: 13123,
 32950261: 13123}

In [17]:
# Ruta de la carpeta que deseas recorrer
carpeta = 'noumbrales'

# Lista para almacenar los nombres de los archivos Excel encontrados
archivos_excel = []

# Recorre la carpeta
for filename in os.listdir(carpeta):
    if filename.endswith('.xlsx') or filename.endswith('.xls'):
        archivos_excel.append(os.path.join(carpeta, filename))
        
acumulador = []

# Ahora, puedes leer los archivos Excel
for archivo_excel in archivos_excel:
    try:
        print(archivo_excel)
        df = pd.read_excel(archivo_excel)
        del df['Unnamed: 0']
        del df['index']
        df.columns = columnas
        df = df.drop(index=[0, 1]).reset_index(drop=True)
        df["semmana_interna"] = int(archivo_excel[29:-5])
        acumulador.append(df.copy())
        #df
        # Haz algo con el DataFrame, por ejemplo, imprimir las primeras filas
        #print(f'Contenido de {archivo_excel}:')
        #print(df.head())
    except Exception as e:
        print(f'Error al leer {archivo_excel}: {str(e)}')

#base = pd.read_excel(r"C:\Users\limc_\carabineros\robot2\referencia\consolidado_noumbrales_ref.xlsx")

noumbrales\avance_noumbrales_319.xlsx
noumbrales\avance_noumbrales_320.xlsx
noumbrales\avance_noumbrales_321.xlsx
noumbrales\avance_noumbrales_322.xlsx
noumbrales\avance_noumbrales_323.xlsx
noumbrales\avance_noumbrales_324.xlsx
noumbrales\avance_noumbrales_325.xlsx
noumbrales\avance_noumbrales_326.xlsx
noumbrales\avance_noumbrales_327.xlsx
noumbrales\avance_noumbrales_328.xlsx
noumbrales\avance_noumbrales_329.xlsx
noumbrales\avance_noumbrales_330.xlsx
noumbrales\avance_noumbrales_331.xlsx

In [18]:
def sacarComas(numero):
    try:
        if(numero < 2 and numero > 1):
            return round(numero * 1000)
        if(numero < 3 and numero > 2):
            return round(numero * 1000)
        if(numero < 4 and numero > 3):
            return round(numero * 1000)
    except:
        pass
    return numero

import numpy as np
def limpiarEspacio(texto):
    try:
        return texto.strip()
    except:
        return np.nan

In [19]:
def getNumber(numero):    
    try:
        numero = str(numero).replace("%","").replace(",",".")
        numero = float(numero)
        return numero 
    except:
        return 0
    
df = pd.concat(acumulador)
df["semmana_interna"] = df["semmana_interna"].round().astype(int).astype(str)
df["nombre final"] = df.apply(lambda x: f"{x.nombre} {x.nombre1} {x.nombre2}".replace("nan",""),axis=1)
del df["nombre"]
del df["nombre1"]
del df["nombre2"]
df["semana"] = df["semmana_interna"].apply(lambda x:variable_cargada[x])
df["semana"] = df["semmana_interna"].apply(lambda x:variable_cargada[x])
df["FechaInicial"] = df["semana"].apply(lambda x:datetime.strptime(x.split(" ")[3], "%d/%m/%Y"))
df["FechaFinal"]   = df["semana"].apply(lambda x:datetime.strptime(x.split(" ")[5], "%d/%m/%Y)"))
df["actual"] = 2024
df["anterior"] = 2023

df["nombre"] = df["nombre final"]
del df["nombre final"]

del df["semmana_interna"]
df["Delito"] = df["Delito"].apply(lambda x: x.strip())
#df["ultimos_7_dias_var"] = df["ultimos_7_dias_var"].apply(getNumber)
#df["ultimos_28_dias_var"] = df["ultimos_28_dias_var"].apply(getNumber)
#df["anno_a_la_fecha_var"] = df["anno_a_la_fecha_var"].apply(getNumber)

for i in ['ultimos_7_dias_anterior', 'ultimos_7_dias', 'ultimos_7_dias_abs',
       'ultimos_7_dias_var', 'ultimos_28_dias_anterior', 'ultimos_28_dias',
       'ultimos_28_dias_abs', 'ultimos_28_dias_var',
       'anno_a_la_fecha_anterior', 'anno_a_la_fecha', 'anno_a_la_fecha_abs',
       'anno_a_la_fecha_var']:
    df[i] = df[i].apply(getNumber)    

merge = df.merge(carabinero,left_on="COD_CUADRANTE_INTERNO",right_on="CUA_CODIGO", how="outer")
merge["titulo"] = merge["CUA_DESCRI"]
merge["COM_CODIGO"] = merge.apply(getComunasAparte,axis=1)
merge2 = merge.rename(columns=diccionarioColumnas)[columnasRef]
diccionarioComunas = {}
for j,i in merge2[["COM_CODIGO","COMUNA"]].drop_duplicates().dropna().iterrows():
    diccionarioComunas[i["COM_CODIGO"]] = i["COMUNA"]

def getComunasAparte2(fila):
    try:
        return diccionarioComunas[int(fila["COM_CODIGO"])]
    except:
        return fila["COMUNA"]
merge2["COMUNA"] = merge2.apply(getComunasAparte2,axis=1)

merge2["año"] = merge2["año"].apply(sacarComas)
merge2["año ant"] = merge2["año ant"].apply(sacarComas)
merge2["año var"] = merge2["año var"].apply(sacarComas)
merge2['mes'] = merge2['mes'].apply(sacarComas)
merge2['mes ant'] = merge2['mes ant'].apply(sacarComas)
merge2['mes var'] = merge2['mes var'].apply(sacarComas)
#merge2['delito'] = merge2['delito'].apply(limpiarEspacio)
listaSemana = list(merge2['id_semana'].unique())[:-1]

#base2 = base[base["id_semana"].apply(lambda x: x not in listaSemana)]
 
#merge3 = pd.concat([merge2,base2])
merge3 = pd.concat([merge2])
merge3['delito'] = merge3['delito'].apply(limpiarEspacio)
merge3.to_excel(r"C:\Users\limc_\carabineros\robot4\consolidado_noumbrales_2024.xlsx", index=False)
print("Termino")

Termino

In [11]:
merge3[merge3["CUA_ANO"].notnull()]

,semana,semana ant,semana var,semana var%,mes,mes ant,mes var,mes var%,año,año ant,...,CUA_ESTADO,CUA_FTERMI,UNI_CODIGO,CUA_ANO,COD_AUPOL,COM_CODIGO,COD_DESTAC,FechaInicial,FechaFinal,COD_CUADRANTE_INTERNO
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,8.212102e+11,2001.0,3315.0,13201.0,8.212102e+11,2024-01-01,2024-01-07,3315151.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,8.212102e+11,2001.0,3315.0,13201.0,8.212102e+11,2024-01-01,2024-01-07,3315151.0
2,4.0,2.0,2.0,100.0,4.0,2.0,2.0,100.0,4.0,2.0,...,1.0,NaN,8.212102e+11,2001.0,3315.0,13201.0,8.212102e+11,2024-01-01,2024-01-07,3315151.0
3,12.0,19.0,-7.0,-36.8,12.0,19.0,-7.0,-36.8,12.0,19.0,...,1.0,NaN,8.212102e+11,2001.0,3315.0,13201.0,8.212102e+11,2024-01-01,2024-01-07,3315151.0
4,6.0,8.0,-2.0,-25.0,6.0,8.0,-2.0,-25.0,6.0,8.0,...,1.0,NaN,8.212102e+11,2001.0,3315.0,13201.0,8.212102e+11,2024-01-01,2024-01-07,3315151.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,8.212106e+11,2001.0,4375.0,13203.0,8.212107e+11,NaT,NaT,NaN
104963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,8.212106e+11,2001.0,4375.0,13203.0,8.212107e+11,NaT,NaT,NaN
104964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,8.110501e+11,2001.0,3172.0,13301.0,8.110501e+11,NaT,NaT,NaN
104965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,8.110501e+11,2001.0,3172.0,13301.0,8.110501e+11,NaT,NaT,NaN
104966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,8.110501e+11,2001.0,3172.0,13301.0,8.110501e+11,NaT,NaT,NaN

In [ ]:
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2022.xlsx

In [10]:
for i in range(2008,2025):
    print(f"https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_{i}.xlsx")

https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2008.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2009.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2010.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2011.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2012.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2013.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2014.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2015.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2016.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2017.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2018.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2019.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2020.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2021.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2022.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2023.xlsx
https://raw.githubusercontent.com/Sud-Austral/URGENCIA_DATA_ACTION/main/historico_urgencias/data_urgencia_2024.xlsx

In [12]:
#https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1990.xlsx
    
for i in range(1990,2025):
    print(f"https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_{i}.xlsx")

https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1990.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1991.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1992.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1993.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1994.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1995.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1996.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1997.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1998.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_1999.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2000.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2001.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2002.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2003.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2004.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2005.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2006.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2007.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2008.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2009.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2010.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2011.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2012.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2013.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2014.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2015.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2016.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2017.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2018.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2019.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2020.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2021.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2022.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2023.xlsx
https://raw.githubusercontent.com/Sud-Austral/defunciones_minsal/main/data/defunciones_2024.xlsx

In [9]:
merge3.columns

Index(['semana', 'semana ant', 'semana var', 'semana var%', 'mes', 'mes ant',
       'mes var', 'mes var%', 'año', 'año ant', 'año var', 'año var%',
       'delito', 'informacion', 'id_semana', 'actual-año', 'anterior-año',
       'Cuad_titulo', 'CUA_CODIGO', 'COMUNA', 'UNIDAD', 'DESTACAMEN',
       'PREFECTURA', 'ZONA', 'NUM_CUAD', 'CUA_DESCRI', 'CUA_TIPO',
       'CUA_ESTADO', 'CUA_FTERMI', 'UNI_CODIGO', 'CUA_ANO', 'COD_AUPOL',
       'COM_CODIGO', 'COD_DESTAC', 'FechaInicial', 'FechaFinal',
       'COD_CUADRANTE_INTERNO'],
      dtype='object')

In [11]:
naty = merge3[merge3['CUA_CODIGO'] == 39582212]

In [12]:
naty['id_semana'].unique()

array(['SEMANA 01/2024 (del 01/01/2024 al 07/01/2024)',
       'SEMANA 02/2024 (del 08/01/2024 al 14/01/2024)',
       'SEMANA 03/2024 (del 15/01/2024 al 21/01/2024)'], dtype=object)

In [17]:
naty[naty['id_semana'] == 'SEMANA 03/2024 (del 15/01/2024 al 21/01/2024)'][["semana", 'año','delito','id_semana','UNIDAD']]

,semana,año,delito,id_semana,UNIDAD
46920,0.0,0.0,HOMICIDIOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46921,0.0,0.0,VIOLACIONES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46922,0.0,1.0,LESIONES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46923,2.0,9.0,ROBOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46924,2.0,8.0,ROBOS CON VIOLENCIA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46925,0.0,2.0,ROBO CON VIOLENCIA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46926,2.0,5.0,ROBO CON INTIMIDACIÓN,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46927,0.0,0.0,ROBO POR SORPRESA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46928,0.0,1.0,ROBO VIOLENTO DE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46929,0.0,1.0,ROBOS CON FUERZA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46930,0.0,0.0,ROBO DE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46931,0.0,0.0,ROBO DE OBJETO DE O DESDE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46932,0.0,1.0,ROBO EN LUGAR HABITADO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46933,0.0,0.0,ROBO EN LUGAR NO HABITADO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46934,0.0,0.0,OTROS ROBOS CON FUERZA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46935,2.0,4.0,HURTOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46936,4.0,14.0,TOTALES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46937,0.0,0.0,HOMICIDIOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46938,0.0,0.0,VIOLACIONES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46939,0.0,1.0,LESIONES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46940,0.0,0.0,ROBOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46941,0.0,0.0,ROBOS CON VIOLENCIA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46942,0.0,0.0,ROBO CON VIOLENCIA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46943,0.0,0.0,ROBO CON INTIMIDACIÓN,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46944,0.0,0.0,ROBO POR SORPRESA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46945,0.0,0.0,ROBO VIOLENTO DE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46946,0.0,0.0,ROBOS CON FUERZA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46947,0.0,0.0,ROBO DE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46948,0.0,0.0,ROBO DE OBJETO DE O DESDE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46949,0.0,0.0,ROBO EN LUGAR HABITADO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46950,0.0,0.0,ROBO EN LUGAR NO HABITADO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46951,0.0,0.0,OTROS ROBOS CON FUERZA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46952,0.0,0.0,HURTOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46953,0.0,1.0,TOTALES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46954,0.0,0.0,HOMICIDIOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46955,0.0,0.0,VIOLACIONES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46956,0.0,1.0,LESIONES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46957,0.0,0.0,ROBOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46958,0.0,0.0,ROBOS CON VIOLENCIA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46959,0.0,0.0,ROBO CON VIOLENCIA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46960,0.0,0.0,ROBO CON INTIMIDACIÓN,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46961,0.0,0.0,ROBO POR SORPRESA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46962,0.0,0.0,ROBO VIOLENTO DE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46963,0.0,0.0,ROBOS CON FUERZA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46964,0.0,0.0,ROBO DE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46965,0.0,0.0,ROBO DE OBJETO DE O DESDE VEHÍCULO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46966,0.0,0.0,ROBO EN LUGAR HABITADO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46967,0.0,0.0,ROBO EN LUGAR NO HABITADO,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46968,0.0,0.0,OTROS ROBOS CON FUERZA,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46969,0.0,0.0,HURTOS,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU
46970,0.0,1.0,TOTALES,SEMANA 03/2024 (del 15/01/2024 al 21/01/2024),52A. COM. RINCONADA DE MAIPU

In [ ]:
#39582212

In [ ]:
listaSemana = list(merge2['id_semana'].unique())[:-1]

base[base["id_semana"].apply(lambda x: x not in listaSemana)]["id_semana"].unique()

In [ ]:
base["id_semana"][0] in list(merge2['id_semana'].unique())[:-1]

In [ ]:
base["id_semana"][0]

In [ ]:
for i in merge3['id_semana'].sort_values().unique():
    if(i is not np.nan):
        print(i,merge3[merge3['id_semana'] == i].shape)

In [ ]:
for i in merge2['id_semana'].sort_values().unique():
    if(i is not np.nan):
        print(i,merge2[merge2['id_semana'] == i].shape)

In [8]:
indice = 0
suma = 0
for i in merge3['id_semana'].sort_values().unique():
    if(i is not np.nan and 17493 != merge3[merge3['id_semana'] == i].shape[0]):
        print(indice,i,merge3[merge3['id_semana'] == i].shape)
        indice += 1
        suma += abs(17493 - merge3[merge3['id_semana'] == i].shape[0])
print(suma / indice)

ZeroDivisionError: division by zero

In [13]:
indice

11

In [12]:
merge3.shape

(909807, 41)

In [14]:
merge3['id_semana'].sort_values().unique()

array(['SEMANA 01/2023 (del 01/01/2023 al 01/01/2023)',
       'SEMANA 02/2023 (del 02/01/2023 al 08/01/2023)',
       'SEMANA 03/2023 (del 09/01/2023 al 15/01/2023)',
       'SEMANA 04/2023 (del 16/01/2023 al 22/01/2023)',
       'SEMANA 05/2023 (del 23/01/2023 al 29/01/2023)',
       'SEMANA 07/2023 (del 06/02/2023 al 12/02/2023)',
       'SEMANA 08/2023 (del 13/02/2023 al 19/02/2023)',
       'SEMANA 09/2023 (del 20/02/2023 al 26/02/2023)',
       'SEMANA 10/2023 (del 27/02/2023 al 05/03/2023)',
       'SEMANA 11/2023 (del 06/03/2023 al 12/03/2023)',
       'SEMANA 12/2023 (del 13/03/2023 al 19/03/2023)',
       'SEMANA 13/2023 (del 20/03/2023 al 26/03/2023)',
       'SEMANA 14/2023 (del 27/03/2023 al 02/04/2023)',
       'SEMANA 15/2023 (del 03/04/2023 al 09/04/2023)',
       'SEMANA 16/2023 (del 10/04/2023 al 16/04/2023)',
       'SEMANA 17/2023 (del 17/04/2023 al 23/04/2023)',
       'SEMANA 18/2023 (del 24/04/2023 al 30/04/2023)',
       'SEMANA 19/2023 (del 01/05/2023 al 07/05/2023)',
       'SEMANA 20/2023 (del 08/05/2023 al 14/05/2023)',
       'SEMANA 21/2023 (del 15/05/2023 al 21/05/2023)',
       'SEMANA 22/2023 (del 22/05/2023 al 28/05/2023)',
       'SEMANA 23/2023 (del 29/05/2023 al 04/06/2023)',
       'SEMANA 24/2023 (del 05/06/2023 al 11/06/2023)',
       'SEMANA 25/2023 (del 12/06/2023 al 18/06/2023)',
       'SEMANA 26/2023 (del 19/06/2023 al 25/06/2023)',
       'SEMANA 27/2023 (del 26/06/2023 al 02/07/2023)',
       'SEMANA 28/2023 (del 03/07/2023 al 09/07/2023)',
       'SEMANA 29/2023 (del 10/07/2023 al 16/07/2023)',
       'SEMANA 30/2023 (del 17/07/2023 al 23/07/2023)',
       'SEMANA 31/2023 (del 24/07/2023 al 30/07/2023)',
       'SEMANA 32/2023 (del 31/07/2023 al 06/08/2023)',
       'SEMANA 33/2023 (del 07/08/2023 al 13/08/2023)',
       'SEMANA 34/2023 (del 14/08/2023 al 20/08/2023)',
       'SEMANA 35/2023 (del 21/08/2023 al 27/08/2023)',
       'SEMANA 36/2023 (del 28/08/2023 al 03/09/2023)',
       'SEMANA 37/2023 (del 04/09/2023 al 10/09/2023)',
       'SEMANA 38/2023 (del 11/09/2023 al 17/09/2023)',
       'SEMANA 39/2023 (del 18/09/2023 al 24/09/2023)',
       'SEMANA 40/2023 (del 25/09/2023 al 01/10/2023)',
       'SEMANA 41/2023 (del 02/10/2023 al 08/10/2023)',
       'SEMANA 42/2023 (del 09/10/2023 al 15/10/2023)',
       'SEMANA 43/2023 (del 16/10/2023 al 22/10/2023)',
       'SEMANA 44/2023 (del 23/10/2023 al 29/10/2023)',
       'SEMANA 45/2023 (del 30/10/2023 al 05/11/2023)',
       'SEMANA 46/2023 (del 06/11/2023 al 12/11/2023)',
       'SEMANA 47/2023 (del 13/11/2023 al 19/11/2023)',
       'SEMANA 48/2023 (del 20/11/2023 al 26/11/2023)',
       'SEMANA 49/2023 (del 27/11/2023 al 03/12/2023)',
       'SEMANA 50/2023 (del 04/12/2023 al 10/12/2023)', nan], dtype=object)

In [9]:
variable_cargada

{'306': 'SEMANA 41/2023 (del 02/10/2023 al 08/10/2023)',
 '305': 'SEMANA 40/2023 (del 25/09/2023 al 01/10/2023)',
 '304': 'SEMANA 39/2023 (del 18/09/2023 al 24/09/2023)',
 '303': 'SEMANA 38/2023 (del 11/09/2023 al 17/09/2023)',
 '302': 'SEMANA 37/2023 (del 04/09/2023 al 10/09/2023)',
 '301': 'SEMANA 36/2023 (del 28/08/2023 al 03/09/2023)',
 '300': 'SEMANA 35/2023 (del 21/08/2023 al 27/08/2023)',
 '299': 'SEMANA 34/2023 (del 14/08/2023 al 20/08/2023)',
 '298': 'SEMANA 33/2023 (del 07/08/2023 al 13/08/2023)',
 '297': 'SEMANA 32/2023 (del 31/07/2023 al 06/08/2023)',
 '296': 'SEMANA 31/2023 (del 24/07/2023 al 30/07/2023)',
 '295': 'SEMANA 30/2023 (del 17/07/2023 al 23/07/2023)',
 '294': 'SEMANA 29/2023 (del 10/07/2023 al 16/07/2023)',
 '293': 'SEMANA 28/2023 (del 03/07/2023 al 09/07/2023)',
 '292': 'SEMANA 27/2023 (del 26/06/2023 al 02/07/2023)',
 '291': 'SEMANA 26/2023 (del 19/06/2023 al 25/06/2023)',
 '290': 'SEMANA 25/2023 (del 12/06/2023 al 18/06/2023)',
 '289': 'SEMANA 24/2023 (del 05/06/2023 al 11/06/2023)',
 '288': 'SEMANA 23/2023 (del 29/05/2023 al 04/06/2023)',
 '287': 'SEMANA 22/2023 (del 22/05/2023 al 28/05/2023)',
 '286': 'SEMANA 21/2023 (del 15/05/2023 al 21/05/2023)',
 '285': 'SEMANA 20/2023 (del 08/05/2023 al 14/05/2023)',
 '284': 'SEMANA 19/2023 (del 01/05/2023 al 07/05/2023)',
 '283': 'SEMANA 18/2023 (del 24/04/2023 al 30/04/2023)',
 '282': 'SEMANA 17/2023 (del 17/04/2023 al 23/04/2023)',
 '281': 'SEMANA 16/2023 (del 10/04/2023 al 16/04/2023)',
 '280': 'SEMANA 15/2023 (del 03/04/2023 al 09/04/2023)',
 '279': 'SEMANA 14/2023 (del 27/03/2023 al 02/04/2023)',
 '278': 'SEMANA 13/2023 (del 20/03/2023 al 26/03/2023)',
 '277': 'SEMANA 12/2023 (del 13/03/2023 al 19/03/2023)',
 '276': 'SEMANA 11/2023 (del 06/03/2023 al 12/03/2023)',
 '275': 'SEMANA 10/2023 (del 27/02/2023 al 05/03/2023)',
 '274': 'SEMANA 09/2023 (del 20/02/2023 al 26/02/2023)',
 '273': 'SEMANA 08/2023 (del 13/02/2023 al 19/02/2023)',
 '272': 'SEMANA 07/2023 (del 06/02/2023 al 12/02/2023)',
 '271': 'SEMANA 06/2023 (del 30/01/2023 al 05/02/2023)',
 '270': 'SEMANA 05/2023 (del 23/01/2023 al 29/01/2023)',
 '269': 'SEMANA 04/2023 (del 16/01/2023 al 22/01/2023)',
 '268': 'SEMANA 03/2023 (del 09/01/2023 al 15/01/2023)',
 '267': 'SEMANA 02/2023 (del 02/01/2023 al 08/01/2023)',
 '266': 'SEMANA 01/2023 (del 01/01/2023 al 01/01/2023)',
 '265': 'SEMANA 53/2022 (del 26/12/2022 al 31/12/2022)',
 '264': 'SEMANA 52/2022 (del 19/12/2022 al 25/12/2022)',
 '263': 'SEMANA 51/2022 (del 12/12/2022 al 18/12/2022)',
 '262': 'SEMANA 50/2022 (del 05/12/2022 al 11/12/2022)',
 '261': 'SEMANA 49/2022 (del 28/11/2022 al 04/12/2022)',
 '260': 'SEMANA 48/2022 (del 21/11/2022 al 27/11/2022)',
 '259': 'SEMANA 47/2022 (del 14/11/2022 al 20/11/2022)',
 '258': 'SEMANA 46/2022 (del 07/11/2022 al 13/11/2022)',
 '257': 'SEMANA 45/2022 (del 31/10/2022 al 06/11/2022)',
 '256': 'SEMANA 44/2022 (del 24/10/2022 al 30/10/2022)',
 '255': 'SEMANA 43/2022 (del 17/10/2022 al 23/10/2022)',
 '254': 'SEMANA 42/2022 (del 10/10/2022 al 16/10/2022)',
 '253': 'SEMANA 41/2022 (del 03/10/2022 al 09/10/2022)',
 '252': 'SEMANA 40/2022 (del 26/09/2022 al 02/10/2022)',
 '251': 'SEMANA 39/2022 (del 19/09/2022 al 25/09/2022)',
 '250': 'SEMANA 38/2022 (del 12/09/2022 al 18/09/2022)',
 '249': 'SEMANA 37/2022 (del 05/09/2022 al 11/09/2022)',
 '248': 'SEMANA 36/2022 (del 29/08/2022 al 04/09/2022)',
 '247': 'SEMANA 35/2022 (del 22/08/2022 al 28/08/2022)',
 '246': 'SEMANA 34/2022 (del 15/08/2022 al 21/08/2022)',
 '245': 'SEMANA 33/2022 (del 08/08/2022 al 14/08/2022)',
 '244': 'SEMANA 32/2022 (del 01/08/2022 al 07/08/2022)',
 '243': 'SEMANA 31/2022 (del 25/07/2022 al 31/07/2022)',
 '242': 'SEMANA 30/2022 (del 18/07/2022 al 24/07/2022)',
 '241': 'SEMANA 29/2022 (del 11/07/2022 al 17/07/2022)',
 '240': 'SEMANA 28/2022 (del 04/07/2022 al 10/07/2022)',
 '239': 'SEMANA 27/2022 (del 27/06/2022 al 03/07/2022)',
 '238': 'SEMANA 26/2022 (del 20/06/2022 al 26/06/2022)',
 '237': 'SEMANA 25/2022 (del 13/06/2022 al 19/06/2022)',
 '236': 'SEMANA 24/2022 (del 06/06/2022 al 12/06/2022)',
 '235': 'SEMANA 23/2022 (del 30/05/2022 al 05/06/2022)',
 '234': 'SEMANA 22/2022 (del 23/05/2022 al 29/05/2022)',
 '233': 'SEMANA 21/2022 (del 16/05/2022 al 22/05/2022)',
 '232': 'SEMANA 20/2022 (del 09/05/2022 al 15/05/2022)',
 '231': 'SEMANA 19/2022 (del 02/05/2022 al 08/05/2022)',
 '230': 'SEMANA 18/2022 (del 25/04/2022 al 01/05/2022)',
 '229': 'SEMANA 17/2022 (del 18/04/2022 al 24/04/2022)',
 '228': 'SEMANA 16/2022 (del 11/04/2022 al 17/04/2022)',
 '227': 'SEMANA 15/2022 (del 04/04/2022 al 10/04/2022)',
 '226': 'SEMANA 14/2022 (del 28/03/2022 al 03/04/2022)',
 '225': 'SEMANA 13/2022 (del 21/03/2022 al 27/03/2022)',
 '224': 'SEMANA 12/2022 (del 14/03/2022 al 20/03/2022)',
 '223': 'SEMANA 11/2022 (del 07/03/2022 al 13/03/2022)',
 '222': 'SEMANA 10/2022 (del 28/02/2022 al 06/03/2022)',
 '221': 'SEMANA 09/2022 (del 21/02/2022 al 27/02/2022)',
 '220': 'SEMANA 08/2022 (del 14/02/2022 al 20/02/2022)',
 '219': 'SEMANA 07/2022 (del 07/02/2022 al 13/02/2022)',
 '218': 'SEMANA 06/2022 (del 31/01/2022 al 06/02/2022)',
 '217': 'SEMANA 05/2022 (del 24/01/2022 al 30/01/2022)',
 '216': 'SEMANA 04/2022 (del 17/01/2022 al 23/01/2022)',
 '215': 'SEMANA 03/2022 (del 10/01/2022 al 16/01/2022)',
 '214': 'SEMANA 02/2022 (del 03/01/2022 al 09/01/2022)',
 '213': 'SEMANA 01/2022 (del 01/01/2022 al 02/01/2022)',
 '212': 'SEMANA 53/2021 (del 27/12/2021 al 31/12/2021)',
 '211': 'SEMANA 52/2021 (del 20/12/2021 al 26/12/2021)',
 '210': 'SEMANA 51/2021 (del 13/12/2021 al 19/12/2021)',
 '209': 'SEMANA 50/2021 (del 06/12/2021 al 12/12/2021)',
 '208': 'SEMANA 49/2021 (del 29/11/2021 al 05/12/2021)',
 '207': 'SEMANA 48/2021 (del 22/11/2021 al 28/11/2021)',
 '206': 'SEMANA 47/2021 (del 15/11/2021 al 21/11/2021)',
 '205': 'SEMANA 46/2021 (del 08/11/2021 al 14/11/2021)',
 '204': 'SEMANA 45/2021 (del 01/11/2021 al 07/11/2021)',
 '203': 'SEMANA 44/2021 (del 25/10/2021 al 31/10/2021)',
 '202': 'SEMANA 43/2021 (del 18/10/2021 al 24/10/2021)',
 '201': 'SEMANA 42/2021 (del 11/10/2021 al 17/10/2021)',
 '200': 'SEMANA 41/2021 (del 04/10/2021 al 10/10/2021)',
 '199': 'SEMANA 40/2021 (del 27/09/2021 al 03/10/2021)',
 '198': 'SEMANA 39/2021 (del 20/09/2021 al 26/09/2021)',
 '197': 'SEMANA 38/2021 (del 13/09/2021 al 19/09/2021)',
 '196': 'SEMANA 37/2021 (del 06/09/2021 al 12/09/2021)',
 '195': 'SEMANA 36/2021 (del 30/08/2021 al 05/09/2021)',
 '194': 'SEMANA 35/2021 (del 23/08/2021 al 29/08/2021)',
 '193': 'SEMANA 34/2021 (del 16/08/2021 al 22/08/2021)',
 '192': 'SEMANA 33/2021 (del 09/08/2021 al 15/08/2021)',
 '191': 'SEMANA 32/2021 (del 02/08/2021 al 08/08/2021)',
 '190': 'SEMANA 31/2021 (del 26/07/2021 al 01/08/2021)',
 '189': 'SEMANA 30/2021 (del 19/07/2021 al 25/07/2021)',
 '188': 'SEMANA 29/2021 (del 12/07/2021 al 18/07/2021)',
 '187': 'SEMANA 28/2021 (del 05/07/2021 al 11/07/2021)',
 '186': 'SEMANA 27/2021 (del 28/06/2021 al 04/07/2021)',
 '185': 'SEMANA 26/2021 (del 21/06/2021 al 27/06/2021)',
 '184': 'SEMANA 25/2021 (del 14/06/2021 al 20/06/2021)',
 '183': 'SEMANA 24/2021 (del 07/06/2021 al 13/06/2021)',
 '182': 'SEMANA 23/2021 (del 31/05/2021 al 06/06/2021)',
 '181': 'SEMANA 22/2021 (del 24/05/2021 al 30/05/2021)',
 '180': 'SEMANA 21/2021 (del 17/05/2021 al 23/05/2021)',
 '179': 'SEMANA 20/2021 (del 10/05/2021 al 16/05/2021)',
 '178': 'SEMANA 19/2021 (del 03/05/2021 al 09/05/2021)',
 '177': 'SEMANA 18/2021 (del 26/04/2021 al 02/05/2021)',
 '176': 'SEMANA 17/2021 (del 19/04/2021 al 25/04/2021)',
 '175': 'SEMANA 16/2021 (del 12/04/2021 al 18/04/2021)',
 '174': 'SEMANA 15/2021 (del 05/04/2021 al 11/04/2021)',
 '173': 'SEMANA 14/2021 (del 29/03/2021 al 04/04/2021)',
 '172': 'SEMANA 13/2021 (del 22/03/2021 al 28/03/2021)',
 '171': 'SEMANA 12/2021 (del 15/03/2021 al 21/03/2021)',
 '170': 'SEMANA 11/2021 (del 08/03/2021 al 14/03/2021)',
 '169': 'SEMANA 10/2021 (del 01/03/2021 al 07/03/2021)',
 '168': 'SEMANA 09/2021 (del 22/02/2021 al 28/02/2021)',
 '167': 'SEMANA 08/2021 (del 15/02/2021 al 21/02/2021)',
 '166': 'SEMANA 07/2021 (del 08/02/2021 al 14/02/2021)',
 '165': 'SEMANA 06/2021 (del 01/02/2021 al 07/02/2021)',
 '164': 'SEMANA 05/2021 (del 25/01/2021 al 31/01/2021)',
 '163': 'SEMANA 04/2021 (del 18/01/2021 al 24/01/2021)',
 '162': 'SEMANA 03/2021 (del 11/01/2021 al 17/01/2021)',
 '161': 'SEMANA 02/2021 (del 04/01/2021 al 10/01/2021)',
 '160': 'SEMANA 01/2021 (del 01/01/2021 al 03/01/2021)',
 '159': 'SEMANA 53/2020 (del 28/12/2020 al 31/12/2020)',
 '158': 'SEMANA 52/2020 (del 21/12/2020 al 27/12/2020)',
 '157': 'SEMANA 51/2020 (del 14/12/2020 al 20/12/2020)',
 '156': 'SEMANA 50/2020 (del 07/12/2020 al 13/12/2020)',
 '155': 'SEMANA 49/2020 (del 30/11/2020 al 06/12/2020)',
 '154': 'SEMANA 48/2020 (del 23/11/2020 al 29/11/2020)',
 '153': 'SEMANA 47/2020 (del 16/11/2020 al 22/11/2020)',
 '152': 'SEMANA 46/2020 (del 09/11/2020 al 15/11/2020)',
 '151': 'SEMANA 45/2020 (del 02/11/2020 al 08/11/2020)',
 '150': 'SEMANA 44/2020 (del 26/10/2020 al 01/11/2020)',
 '149': 'SEMANA 43/2020 (del 19/10/2020 al 25/10/2020)',
 '148': 'SEMANA 42/2020 (del 12/10/2020 al 18/10/2020)',
 '147': 'SEMANA 41/2020 (del 05/10/2020 al 11/10/2020)',
 '146': 'SEMANA 40/2020 (del 28/09/2020 al 04/10/2020)',
 '145': 'SEMANA 39/2020 (del 21/09/2020 al 27/09/2020)',
 '144': 'SEMANA 38/2020 (del 14/09/2020 al 20/09/2020)',
 '143': 'SEMANA 37/2020 (del 07/09/2020 al 13/09/2020)',
 '142': 'SEMANA 36/2020 (del 31/08/2020 al 06/09/2020)',
 '141': 'SEMANA 35/2020 (del 24/08/2020 al 30/08/2020)',
 '140': 'SEMANA 34/2020 (del 17/08/2020 al 23/08/2020)',
 '139': 'SEMANA 33/2020 (del 10/08/2020 al 16/08/2020)',
 '138': 'SEMANA 32/2020 (del 03/08/2020 al 09/08/2020)',
 '137': 'SEMANA 31/2020 (del 27/07/2020 al 02/08/2020)',
 '136': 'SEMANA 30/2020 (del 20/07/2020 al 26/07/2020)',
 '135': 'SEMANA 29/2020 (del 13/07/2020 al 19/07/2020)',
 '134': 'SEMANA 28/2020 (del 06/07/2020 al 12/07/2020)',
 '133': 'SEMANA 27/2020 (del 29/06/2020 al 05/07/2020)',
 '132': 'SEMANA 26/2020 (del 22/06/2020 al 28/06/2020)',
 '131': 'SEMANA 25/2020 (del 15/06/2020 al 21/06/2020)',
 '130': 'SEMANA 24/2020 (del 08/06/2020 al 14/06/2020)',
 '129': 'SEMANA 23/2020 (del 01/06/2020 al 07/06/2020)',
 '128': 'SEMANA 22/2020 (del 25/05/2020 al 31/05/2020)',
 '127': 'SEMANA 21/2020 (del 18/05/2020 al 24/05/2020)',
 '126': 'SEMANA 20/2020 (del 11/05/2020 al 17/05/2020)',
 '125': 'SEMANA 19/2020 (del 04/05/2020 al 10/05/2020)',
 '124': 'SEMANA 18/2020 (del 27/04/2020 al 03/05/2020)',
 '123': 'SEMANA 17/2020 (del 20/04/2020 al 26/04/2020)',
 '122': 'SEMANA 16/2020 (del 13/04/2020 al 19/04/2020)',
 '121': 'SEMANA 15/2020 (del 06/04/2020 al 12/04/2020)',
 '120': 'SEMANA 14/2020 (del 30/03/2020 al 05/04/2020)',
 '119': 'SEMANA 13/2020 (del 23/03/2020 al 29/03/2020)',
 '118': 'SEMANA 12/2020 (del 16/03/2020 al 22/03/2020)',
 '117': 'SEMANA 11/2020 (del 09/03/2020 al 15/03/2020)',
 '116': 'SEMANA 10/2020 (del 02/03/2020 al 08/03/2020)',
 '115': 'SEMANA 09/2020 (del 24/02/2020 al 01/03/2020)',
 '114': 'SEMANA 08/2020 (del 17/02/2020 al 23/02/2020)',
 '113': 'SEMANA 07/2020 (del 10/02/2020 al 16/02/2020)',
 '112': 'SEMANA 06/2020 (del 03/02/2020 al 09/02/2020)',
 '111': 'SEMANA 05/2020 (del 27/01/2020 al 02/02/2020)',
 '110': 'SEMANA 04/2020 (del 20/01/2020 al 26/01/2020)',
 '109': 'SEMANA 03/2020 (del 13/01/2020 al 19/01/2020)',
 '108': 'SEMANA 02/2020 (del 06/01/2020 al 12/01/2020)',
 '107': 'SEMANA 01/2020 (del 01/01/2020 al 05/01/2020)',
 '106': 'SEMANA 53/2019 (del 30/12/2019 al 31/12/2019)',
 '105': 'SEMANA 52/2019 (del 23/12/2019 al 29/12/2019)',
 '104': 'SEMANA 51/2019 (del 16/12/2019 al 22/12/2019)',
 '103': 'SEMANA 50/2019 (del 09/12/2019 al 15/12/2019)',
 '102': 'SEMANA 49/2019 (del 02/12/2019 al 08/12/2019)',
 '101': 'SEMANA 48/2019 (del 25/11/2019 al 01/12/2019)',
 '100': 'SEMANA 47/2019 (del 18/11/2019 al 24/11/2019)',
 '99': 'SEMANA 46/2019 (del 11/11/2019 al 17/11/2019)',
 '98': 'SEMANA 45/2019 (del 04/11/2019 al 10/11/2019)',
 '97': 'SEMANA 44/2019 (del 28/10/2019 al 03/11/2019)',
 '96': 'SEMANA 43/2019 (del 21/10/2019 al 27/10/2019)',
 '95': 'SEMANA 42/2019 (del 14/10/2019 al 20/10/2019)',
 '94': 'SEMANA 41/2019 (del 07/10/2019 al 13/10/2019)',
 '93': 'SEMANA 40/2019 (del 30/09/2019 al 06/10/2019)',
 '92': 'SEMANA 39/2019 (del 23/09/2019 al 29/09/2019)',
 '91': 'SEMANA 38/2019 (del 16/09/2019 al 22/09/2019)',
 '90': 'SEMANA 37/2019 (del 09/09/2019 al 15/09/2019)',
 '89': 'SEMANA 36/2019 (del 02/09/2019 al 08/09/2019)',
 '88': 'SEMANA 35/2019 (del 26/08/2019 al 01/09/2019)',
 '87': 'SEMANA 34/2019 (del 19/08/2019 al 25/08/2019)',
 '86': 'SEMANA 33/2019 (del 12/08/2019 al 18/08/2019)',
 '85': 'SEMANA 32/2019 (del 05/08/2019 al 11/08/2019)',
 '84': 'SEMANA 31/2019 (del 29/07/2019 al 04/08/2019)',
 '83': 'SEMANA 30/2019 (del 22/07/2019 al 28/07/2019)',
 '82': 'SEMANA 29/2019 (del 15/07/2019 al 21/07/2019)',
 '81': 'SEMANA 28/2019 (del 08/07/2019 al 14/07/2019)',
 '80': 'SEMANA 27/2019 (del 01/07/2019 al 07/07/2019)',
 '79': 'SEMANA 26/2019 (del 24/06/2019 al 30/06/2019)',
 '78': 'SEMANA 25/2019 (del 17/06/2019 al 23/06/2019)',
 '77': 'SEMANA 24/2019 (del 10/06/2019 al 16/06/2019)',
 '76': 'SEMANA 23/2019 (del 03/06/2019 al 09/06/2019)',
 '75': 'SEMANA 22/2019 (del 27/05/2019 al 02/06/2019)',
 '74': 'SEMANA 21/2019 (del 20/05/2019 al 26/05/2019)',
 '73': 'SEMANA 20/2019 (del 13/05/2019 al 19/05/2019)',
 '72': 'SEMANA 19/2019 (del 06/05/2019 al 12/05/2019)',
 '71': 'SEMANA 18/2019 (del 29/04/2019 al 05/05/2019)',
 '70': 'SEMANA 17/2019 (del 22/04/2019 al 28/04/2019)',
 '69': 'SEMANA 16/2019 (del 15/04/2019 al 21/04/2019)',
 '68': 'SEMANA 15/2019 (del 08/04/2019 al 14/04/2019)',
 '67': 'SEMANA 14/2019 (del 01/04/2019 al 07/04/2019)',
 '66': 'SEMANA 13/2019 (del 25/03/2019 al 31/03/2019)',
 '65': 'SEMANA 12/2019 (del 18/03/2019 al 24/03/2019)',
 '64': 'SEMANA 11/2019 (del 11/03/2019 al 17/03/2019)',
 '63': 'SEMANA 10/2019 (del 04/03/2019 al 10/03/2019)',
 '62': 'SEMANA 09/2019 (del 25/02/2019 al 03/03/2019)',
 '61': 'SEMANA 08/2019 (del 18/02/2019 al 24/02/2019)',
 '60': 'SEMANA 07/2019 (del 11/02/2019 al 17/02/2019)',
 '59': 'SEMANA 06/2019 (del 04/02/2019 al 10/02/2019)',
 '58': 'SEMANA 05/2019 (del 28/01/2019 al 03/02/2019)',
 '57': 'SEMANA 04/2019 (del 21/01/2019 al 27/01/2019)',
 '56': 'SEMANA 03/2019 (del 14/01/2019 al 20/01/2019)',
 '55': 'SEMANA 02/2019 (del 07/01/2019 al 13/01/2019)',
 '54': 'SEMANA 01/2019 (del 01/01/2019 al 06/01/2019)',
 '53': 'SEMANA 53/2018 (del 31/12/2018 al 31/12/2018)',
 '52': 'SEMANA 52/2018 (del 24/12/2018 al 30/12/2018)',
 '51': 'SEMANA 51/2018 (del 17/12/2018 al 23/12/2018)',
 '50': 'SEMANA 50/2018 (del 10/12/2018 al 16/12/2018)',
 '49': 'SEMANA 49/2018 (del 03/12/2018 al 09/12/2018)',
 '48': 'SEMANA 48/2018 (del 26/11/2018 al 02/12/2018)',
 '47': 'SEMANA 47/2018 (del 19/11/2018 al 25/11/2018)',
 '46': 'SEMANA 46/2018 (del 12/11/2018 al 18/11/2018)',
 '45': 'SEMANA 45/2018 (del 05/11/2018 al 11/11/2018)',
 '44': 'SEMANA 44/2018 (del 29/10/2018 al 04/11/2018)',
 '43': 'SEMANA 43/2018 (del 22/10/2018 al 28/10/2018)',
 '42': 'SEMANA 42/2018 (del 15/10/2018 al 21/10/2018)',
 '41': 'SEMANA 41/2018 (del 08/10/2018 al 14/10/2018)',
 '40': 'SEMANA 40/2018 (del 01/10/2018 al 07/10/2018)',
 '39': 'SEMANA 39/2018 (del 24/09/2018 al 30/09/2018)',
 '38': 'SEMANA 38/2018 (del 17/09/2018 al 23/09/2018)',
 '37': 'SEMANA 37/2018 (del 10/09/2018 al 16/09/2018)',
 '36': 'SEMANA 36/2018 (del 03/09/2018 al 09/09/2018)',
 '35': 'SEMANA 35/2018 (del 27/08/2018 al 02/09/2018)',
 '34': 'SEMANA 34/2018 (del 20/08/2018 al 26/08/2018)',
 '33': 'SEMANA 33/2018 (del 13/08/2018 al 19/08/2018)',
 '32': 'SEMANA 32/2018 (del 06/08/2018 al 12/08/2018)',
 '31': 'SEMANA 31/2018 (del 30/07/2018 al 05/08/2018)',
 '30': 'SEMANA 30/2018 (del 23/07/2018 al 29/07/2018)',
 '29': 'SEMANA 29/2018 (del 16/07/2018 al 22/07/2018)',
 '28': 'SEMANA 28/2018 (del 09/07/2018 al 15/07/2018)',
 '27': 'SEMANA 27/2018 (del 02/07/2018 al 08/07/2018)',
 '26': 'SEMANA 26/2018 (del 25/06/2018 al 01/07/2018)',
 '25': 'SEMANA 25/2018 (del 18/06/2018 al 24/06/2018)',
 '24': 'SEMANA 24/2018 (del 11/06/2018 al 17/06/2018)',
 '23': 'SEMANA 23/2018 (del 04/06/2018 al 10/06/2018)',
 '22': 'SEMANA 22/2018 (del 28/05/2018 al 03/06/2018)',
 '21': 'SEMANA 21/2018 (del 21/05/2018 al 27/05/2018)',
 '20': 'SEMANA 20/2018 (del 14/05/2018 al 20/05/2018)',
 '19': 'SEMANA 19/2018 (del 07/05/2018 al 13/05/2018)',
 '18': 'SEMANA 18/2018 (del 30/04/2018 al 06/05/2018)',
 '17': 'SEMANA 17/2018 (del 23/04/2018 al 29/04/2018)',
 '16': 'SEMANA 16/2018 (del 16/04/2018 al 22/04/2018)',
 '15': 'SEMANA 15/2018 (del 09/04/2018 al 15/04/2018)',
 '14': 'SEMANA 14/2018 (del 02/04/2018 al 08/04/2018)',
 '13': 'SEMANA 13/2018 (del 26/03/2018 al 01/04/2018)',
 '12': 'SEMANA 12/2018 (del 19/03/2018 al 25/03/2018)',
 '11': 'SEMANA 11/2018 (del 12/03/2018 al 18/03/2018)',
 '10': 'SEMANA 10/2018 (del 05/03/2018 al 11/03/2018)',
 '9': 'SEMANA 09/2018 (del 26/02/2018 al 04/03/2018)',
 '8': 'SEMANA 08/2018 (del 19/02/2018 al 25/02/2018)',
 '7': 'SEMANA 07/2018 (del 12/02/2018 al 18/02/2018)',
 '6': 'SEMANA 06/2018 (del 05/02/2018 al 11/02/2018)',
 '5': 'SEMANA 05/2018 (del 29/01/2018 al 04/02/2018)',
 '4': 'SEMANA 04/2018 (del 22/01/2018 al 28/01/2018)',
 '3': 'SEMANA 03/2018 (del 15/01/2018 al 21/01/2018)',
 '2': 'SEMANA 02/2018 (del 08/01/2018 al 14/01/2018)',
 '1': 'SEMANA 01/2018 (del 01/01/2018 al 07/01/2018)',
 '307': 'SEMANA 42/2023 (del 09/10/2023 al 15/10/2023)',
 '308': 'SEMANA 43/2023 (del 16/10/2023 al 22/10/2023)',
 '309': 'SEMANA 44/2023 (del 23/10/2023 al 29/10/2023)',
 '310': 'SEMANA 45/2023 (del 30/10/2023 al 05/11/2023)',
 '311': 'SEMANA 46/2023 (del 06/11/2023 al 12/11/2023)',
 '312': 'SEMANA 47/2023 (del 13/11/2023 al 19/11/2023)',
 '313': 'SEMANA 48/2023 (del 20/11/2023 al 26/11/2023)',
 '314': 'SEMANA 49/2023 (del 27/11/2023 al 03/12/2023)',
 '315': 'SEMANA 50/2023 (del 04/12/2023 al 10/12/2023)'}

In [10]:
df = pd.read_csv(r"C:\Users\limc_\OneDrive\Escritorio\Frecuencia_Corregido_Final\Frecuencia_Corregido_Final.csv")
df

,delito,Medida,Tipo de datos,grupo delictual,CodigoDelito,CodigoGrupDel,Codreg,Codprov,Codcom,Mes/Año,Frecuencia,Mes/Año Formato Fecha
0,Lesiones leves,Tasa Cada 100.000 Habitantes,Aprehendidos,Delitos de mayor connotación social,3,1,10,104,10404,9/2021,0,"01 Sep, 2021"
1,Robo de objetos de o desde vehículo,Frecuencia,Detenciones,Delitos de mayor connotación social,7,1,6,61,6114,9/2021,0,"01 Sep, 2021"
2,Robo de objetos de o desde vehículo,Tasa Cada 100.000 Habitantes,Detenciones,Delitos de mayor connotación social,7,1,6,61,6114,9/2021,0,"01 Sep, 2021"
3,Robo de vehículo motorizado,Frecuencia,Aprehendidos,Delitos de mayor connotación social,8,1,6,61,6114,9/2021,0,"01 Sep, 2021"
4,Robo de vehículo motorizado,Tasa Cada 100.000 Habitantes,Aprehendidos,Delitos de mayor connotación social,8,1,6,61,6114,9/2021,0,"01 Sep, 2021"
...,...,...,...,...,...,...,...,...,...,...,...,...
19070323,Otras incivilidades,Frecuencia,Denuncias,Incivilidades,24,3,13,131,13104,1/2005,13,"01 Jan, 2005"
19070324,Desórdenes,Tasa Cada 100.000 Habitantes,Denuncias,Incivilidades,22,3,9,91,9110,1/2005,0,"01 Jan, 2005"
19070325,Violencia intrafamiliar a adulto mayor,Frecuencia,Aprehendidos,Violencia intrafamiliar,29,6,5,51,5104,1/2005,0,"01 Jan, 2005"
19070326,Robo de vehículo motorizado,Tasa Cada 100.000 Habitantes,Detenciones,Delitos de mayor connotación social,8,1,8,83,8302,1/2005,0,"01 Jan, 2005"
19070327,Violencia intrafamiliar a mujer,Frecuencia,Aprehendidos,Violencia intrafamiliar,31,6,13,131,13107,1/2005,2,"01 Jan, 2005"

In [8]:
base = "https://www.cplt.cl/transparencia_activa/datoabierto/archivos/"
deseadas =["Nombres","Paterno","Materno","organismo_nombre",'anyo', 'Mes','tipo_calificacionp']


TA_PersonalPlanta                       = f"{base}TA_PersonalPlanta.csv"
TA_PersonalContrata                     = f"{base}TA_PersonalContrata.csv"
TA_PersonalCodigotrabajo                = f"{base}TA_PersonalCodigotrabajo.csv"
TA_PersonalContratohonorarios           = f"{base}TA_PersonalContratohonorarios.csv"

PersonalPlantaDICT                = deseadas+["remuliquida_mensual",'Tipo cargo', 'remuneracionbruta_mensual']
PersonalContrataDICT              = deseadas+["remuliquida_mensual",'Tipo cargo','remuneracionbruta_mensual'] 
PersonalCodigotrabajoDICT         = deseadas+["remuliquida_mensual",'Tipo cargo', 'remuneracionbruta_mensual']
PersonalContratohonorariosDICT    = deseadas+['remuliquida_mensual','tipo_pago','num_cuotas','remuneracionbruta']


import pandas as pd
from datetime import datetime
import re

In [11]:

def getDF(url,columnas):
    return pd.read_csv(url, low_memory=False,sep=";",encoding="latin",usecols=columnas, nrows=2)

In [12]:
df = getDF(TA_PersonalPlanta              ,PersonalPlantaDICT)
df

,organismo_nombre,anyo,Mes,Nombres,Paterno,Materno,tipo_calificacionp,Tipo cargo,remuneracionbruta_mensual,remuliquida_mensual
0,Municipalidad de Puchuncaví,2014,Julio,CARMEN GLORIA,TAPIA,VIDAL,INGENIERO EJECUCION,ATENCION DE PUBLICO OMIL GERENCIA DESARROLLO E...,"1072452,0",NaN
1,Municipalidad de Puchuncaví,2014,Julio,PAOLA ANDREA,ARANGUIZ,PEZO,SECRETARIA ADMINISTRATIVA,SECRETARIA GERENCIA DE VIVIENDA SOCIAL,"455774,0",NaN