In [1]:
import pandas as pd

In [9]:
archivo_excel = pd.ExcelFile(r"C:\Users\limc_\Downloads\LOCALIZA_Todos2.xlsx")
nombres_hojas = archivo_excel.sheet_names
nombres_hojas

['Guatemala',
 'Honduras',
 'Chile',
 'El Salvador',
 'Panamá',
 'Costa Rica',
 'Rep Dominicana',
 'Belice',
 'Nicaragua']

In [10]:
for i in nombres_hojas:

    df = pd.read_excel(r"C:\Users\limc_\Downloads\LOCALIZA_Todos2.xlsx", sheet_name=i,skiprows=2,header=1)
    print(i,df.columns)

Guatemala Index(['Unnamed: 0', 'País', 'Admin1_Tipo', 'Coddep', 'Departamento',
       'Admin2_Tipo', 'Codmun', 'Municipio'],
      dtype='object')
Honduras Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Coddep',
       'Departamento', 'Admin2_Tipo', 'Codmun', 'Municipio'],
      dtype='object')
Chile Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Codreg', 'Región',
       'Admin2_Tipo', 'Codcom', 'Comuna'],
      dtype='object')
El Salvador Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Coddep',
       'Departamento', 'Admin2_Tipo', 'Codmun', 'Municipio'],
      dtype='object')
Panamá Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Codprov',
       'Provincia', 'Admin2_Tipo', 'Coddist', 'Distrito'],
      dtype='object')
Costa Rica Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Codprov',
       'Provincia', 'Admin2_Tipo', 'Codcan', 'Cantón'],
      dtype='object')
Rep Dominicana Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Codprov',
       'Provincia', 'Admin2_Tipo', 'Codmun', 'Municipio'],
      dtype='object')
Belice Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Coddist',
       'Distrito', 'Admin2_Tipo', 'Codmun', 'Municipio'],
      dtype='object')
Nicaragua Index(['Unnamed: 0', 'Unnamed: 1', 'País', 'Admin1_Tipo', 'Coddep',
       'Departamento', 'Admin2_Tipo', 'Codmun', 'Municipio'],
      dtype='object')

In [7]:
pd.read_excel(r"C:\Users\limc_\Downloads\LOCALIZA_Todos.xlsx", sheet_name="Guatemala",skiprows=1,header=1)

,Unnamed: 0,País,Admin1_Tipo,Coddep,Departamento,Admin2_Tipo,Codmun,Municipio
0,NaN,Guatemala,Departamento,1,Guatemala,Municipio,101,Guatemala
1,NaN,Guatemala,Departamento,1,Guatemala,Municipio,102,Santa Catarina Pinula
2,NaN,Guatemala,Departamento,1,Guatemala,Municipio,103,San José Pinula
3,NaN,Guatemala,Departamento,1,Guatemala,Municipio,104,San José del Golfo
4,NaN,Guatemala,Departamento,1,Guatemala,Municipio,105,Palencia
...,...,...,...,...,...,...,...,...
336,NaN,Guatemala,Departamento,22,Jutiapa,Municipio,2213,Conguaco
337,NaN,Guatemala,Departamento,22,Jutiapa,Municipio,2214,Moyuta
338,NaN,Guatemala,Departamento,22,Jutiapa,Municipio,2215,Pasaco
339,NaN,Guatemala,Departamento,22,Jutiapa,Municipio,2216,San José Acatempa
340,NaN,Guatemala,Departamento,22,Jutiapa,Municipio,2217,Quesada

In [8]:
pd.read_excel(r"C:\Users\limc_\Downloads\LOCALIZA_Todos.xlsx", sheet_name="Honduras",skiprows=1,header=1)

,Unnamed: 0,Unnamed: 1,País,Admin1_Tipo,Coddep,Departamento,Admin2_Tipo,Codmun,Municipio
0,NaN,NaN,Honduras,Departamento,1,ATLÁNTIDA,Municipio,101,LA CEIBA
1,NaN,NaN,Honduras,Departamento,1,ATLÁNTIDA,Municipio,102,EL PORVENIR
2,NaN,NaN,Honduras,Departamento,1,ATLÁNTIDA,Municipio,103,ESPARTA
3,NaN,NaN,Honduras,Departamento,1,ATLÁNTIDA,Municipio,104,JUTIAPA
4,NaN,NaN,Honduras,Departamento,1,ATLÁNTIDA,Municipio,105,LA MASICA
...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,Honduras,Departamento,18,YORO,Municipio,1807,OLANCHITO
307,NaN,NaN,Honduras,Departamento,18,YORO,Municipio,1808,SANTA RITA
308,NaN,NaN,Honduras,Departamento,18,YORO,Municipio,1809,SULACO
309,NaN,NaN,Honduras,Departamento,18,YORO,Municipio,1810,VICTORIA
310,NaN,NaN,Honduras,Departamento,18,YORO,Municipio,1811,YORITO

In [21]:
acumulado1 = []
acumulado2 = []

In [26]:
acumulado1 = []
acumulado2 = []
for i in nombres_hojas:
    print(i)
    df = pd.read_excel(r"C:\Users\limc_\Downloads\LOCALIZA_Todos3.xlsx", sheet_name=i,skiprows=2,header=1)
    for i,j in df[["País","Departamento"]].drop_duplicates().iterrows():
        diccionario = {"list_name":"gg5ko71","name":j["Departamento"]+"-"+j["País"],"label":j["Departamento"]+"-"+j["País"],"state":j["País"]}
        acumulado1.append(diccionario.copy())
    for i,j in df.iterrows():
        diccionario = {"list_name":"gg5ko72","name":j["Municipio"]+"-"+j["Departamento"],"label":j["Municipio"]+"-"+j["Departamento"],"state":j["País"],"county":j["Departamento"]+"-"+j["País"]}
        acumulado2.append(diccionario.copy())
        
pd.DataFrame(acumulado1).drop_duplicates().to_excel("primeraParte.xlsx", index=False)
pd.DataFrame(acumulado2).drop_duplicates().to_excel("segundaParte.xlsx", index=False)

Guatemala
Honduras
Chile
El Salvador
Panamá
Costa Rica
Rep Dominicana
Belice
Nicaragua